defmodule ServantWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :servant

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_servant_key",
    signing_salt: "ZbJqQ+IZ",
    same_site: "Lax"
  ]

  # The LiveView socket exists only for the dev-only LiveDashboard; this is an
  # API-only app with no LiveView otherwise.
  if Application.compile_env(:servant, :dev_routes) do
    socket "/live", Phoenix.LiveView.Socket,
      websocket: [connect_info: [session: @session_options]],
      longpoll: [connect_info: [session: @session_options]]
  end

  socket "/socket", ServantWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :servant,
    gzip: not code_reloading?,
    only: ServantWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # User files (/files, /uploads) are served by an authenticated controller in
  # the router (ServantWeb.FilesController) — never as unauthenticated statics.

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :servant
  end

  if Application.compile_env(:servant, :dev_routes) do
    plug Phoenix.LiveDashboard.RequestLogger,
      param_key: "request_logger",
      cookie_key: "request_logger"
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]
  plug ServantWeb.Plugs.AccessLog

  plug Plug.Parsers,
    # Cap JSON/urlencoded bodies at 10MB; multipart gets its own budget slightly
    # above the 1GB upload limit (enforced in UploadController).
    parsers: [:urlencoded, :json, {:multipart, length: 1_100_000_000}],
    pass: ["*/*"],
    length: 10_000_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ServantWeb.Router
end
