defmodule ServantWeb.Endpoint do
  @moduledoc false

  use Phoenix.Endpoint, otp_app: :servant

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_servant_key",
    signing_salt: "ZbJqQ+IZ",
    same_site: "Lax"
  ]

  # The LiveView socket exists only for the dev-only LiveDashboard; this is an
  # API-only app with no LiveView otherwise.
  if Application.compile_env(:servant, :dev_routes) do
    socket "/live", Phoenix.LiveView.Socket,
      websocket: [connect_info: [session: @session_options]],
      longpoll: [connect_info: [session: @session_options]]
  end

  socket "/socket", ServantWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :servant,
    gzip: not code_reloading?,
    only: ServantWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # User files (/files, /uploads) are served by an authenticated controller in
  # the router (ServantWeb.FilesController), never as unauthenticated statics.

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :servant
  end

  if Application.compile_env(:servant, :dev_routes) do
    plug Phoenix.LiveDashboard.RequestLogger,
      param_key: "request_logger",
      cookie_key: "request_logger"
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Behind the documented nginx deployment every request arrives from
  # 127.0.0.1; RemoteIp restores the real client address from
  # X-Forwarded-For (loopback/private peers count as proxies by default,
  # and the header is ignored when the peer is a direct public client),
  # so the per-IP auth throttle and the access log see actual clients.
  plug RemoteIp
  plug ServantWeb.Plugs.AccessLog

  plug Plug.Parsers,
    # JSON-only API (uploads are multipart). Deliberately no :urlencoded parser:
    # a cross-site HTML form posts application/x-www-form-urlencoded as a CORS
    # "simple" request (no preflight); parsing it would let such a form reach
    # POST /api/auth/login and set the SameSite=Lax cookie (login CSRF). Without
    # the parser those bodies stay unparsed and the endpoints 422.
    # Cap JSON at 10MB; multipart gets its own budget just above the 1GB upload
    # limit (enforced in UploadController).
    parsers: [:json, {:multipart, length: 1_100_000_000}],
    pass: ["*/*"],
    length: 10_000_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ServantWeb.Router
end
